name: CI

on:
    push:
        branches: [main]
    pull_request:

jobs:
    js-css:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm
            - run: npm ci
            - run: npm run eslint:js
            - run: npm run lint:scss
            - run: npm run build

    php:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: themes/boilerplate
        steps:
            - uses: actions/checkout@v4
            - uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.3'
                  tools: composer
            - run: composer install --prefer-dist --no-progress
            - run: composer qa
