name: Deploy to Staging

on:
    push:
        branches: [staging]
    workflow_dispatch:

jobs:
    deploy-staging:
        uses: Unknownsock/gha-wp-deploy/.github/workflows/deploy.yml@v1
        with:
            environment: staging
        secrets:
            STAGING_FTP_USERNAME: ${{ secrets.STAGING_FTP_USERNAME }}
            STAGING_FTP_PASSWORD: ${{ secrets.STAGING_FTP_PASSWORD }}
